title = "Nivox's Hub"
baseURL = "https://nivox.github.io"
languageCode = "en-us"
theme = "anankegit"
themesDir = "themes"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

#[languages]
#  [languages.en]
#    title = "My blog"
#    weight = 1
#    contentDir = "content/en"
  
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Andrea Zito"
  favicon = ""
  site_logo = ""
  description = "Ramblings about software engineering... mostly"
  facebook = ""
  twitter = "https://twitter.com/nivox"
  instagram = ""
  youtube = ""
  github = "https://github.com/nivox"
  gitlab = "https://gitlab.com/nivox"
  linkedin = "https://linkedin.com/in/andreazito"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cover.jpg"
  recent_posts_number = 2
