name: Build Hugo Site
on: [push]
jobs:
  build-hugo-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify --environment production -d .hugo-build
    - name: Push public site
      run: |
        git fetch
        git checkout live
        rm -rf *
        git config --global user.name 'Hugo Build Action'
        git config --global user.email 'nivox@users.noreply.github.com'
        git add .
        git commit -m "Hugo Build"
        git push